In [1]:
#Load Python Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Load Data
file='ex1data2.txt'
data=np.loadtxt(file,delimiter=',')
X=data[:,:-1]
y=data[:,-1] 
y=y[:,np.newaxis] #1D to 2D array
m=X.shape[0] #no. of training examples
n=data.shape[1] #no. of feature

In [3]:
#Feature normalization
mu= np.mean(X, axis=0)
sigma=X.max(axis=0)-X.min(axis=0)
x_norm= (X-mu)/sigma
X = x_norm

In [4]:
#add ones to X
x0=np.ones((m,1))
X=np.concatenate((x0,X),axis=1)
theta=np.zeros((n,1))

In [5]:
#Computation
alpha=0.01
iterations=50000

h=np.matmul(X,theta)
cost= sum((h-y)**2)/(2*m)

for i in range(iterations):
    grad= sum((h-y)*X)
    grad=grad.reshape(n,1)
    theta= theta-((alpha/m)*grad)
    h=np.matmul(X,theta)
    cost= sum((h-y)**2)/(2*m)
    
print('Cost: \n',cost)
print('Theta: \n',theta)
    


Cost: 
 [2.04328007e+09]
Theta: 
 [[340412.65957447]
 [504747.34962916]
 [-34912.80713998]]


In [6]:
# Calculating theta from normal equation
X_temp=np.matmul(X.T,X)
theta_normal=np.matmul(np.linalg.inv(X_temp),np.matmul(X.T,y));
h_normal = np.matmul(X,theta_normal)
cost_normal= sum((h_normal-y)**2)/(2*m)

print('Cost_normal: \n',cost_normal)
print('Theta_normal: \n',theta_normal)

Cost_normal: 
 [2.04328005e+09]
Theta_normal: 
 [[340412.65957447]
 [504777.90398791]
 [-34952.07644931]]


In [7]:
#Calculating using Scikit Learn
from sklearn.linear_model import LinearRegression
model=LinearRegression()
#Train Model
model.fit(X,y)

#Hypothessis
theta0=model.intercept_
theta_rem= model.coef_[0,1:]

theta_scikit=np.concatenate((theta0,theta_rem))
theta_scikit=theta_scikit[:,np.newaxis]
h_scikit=np.matmul(X,theta_scikit)
cost_scikit= sum((h_scikit-y)**2)/(2*m)

print('Cost_Scikit: \n',cost_scikit)
print('Theta_Scikit: \n',theta_scikit)


Cost_Scikit: 
 [2.04328005e+09]
Theta_Scikit: 
 [[340412.65957447]
 [504777.90398791]
 [-34952.07644931]]
